# 서버 설정
server:
  # 내장 톰캣 서버의 포트 번호 설정
  port: 80
  servlet:
    # HTTP 요청 및 응답의 인코딩 변경
    encoding:
      charset: UTF-8
      enabled: true
      force: true


# 스프링 설정
spring:
  application:
    # 애플리케이션 이름 설정
    name: gopp-v1
  main:
    # 스프링 부트 애플리케이션 구동시 출력되는 시작 배너 끄기
    banner-mode: OFF
  # 타임리프 설정 : 웹 브라우저의 새로고침을 통해 변경된 화면단 적용을 위해 템플릿 경로와 캐시값 설정
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    mode: HTML
    # 화면단 수정 내용의 즉시 반영을 위한 캐시 설정을 false로 설정하되, 개발 완료시엔 true로 변경
    cache: false
  # 웹 정적 리소스 설정 : 웹 브라우저의 새로고침을 통해
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
      # 웹 브라우저의 캐시 시간 지정
      cache:
        period: 36000
  # 데이터베이스 연결 정보 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/gopp_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: suihin
    password: tq5033
    driver-class-name: org.mariadb.jdbc.Driver


# 마이바티스 설정
mybatis:
  # 서버 구동시, 마이바티스의 동작 제어를 위한 값 설정
  configuration:
    # 마이바티스 캐싱 기능 끄기
    cache-enabled: false  # 매퍼 네임스페이스 단위로 동작되는 캐시 끄기
    local-cache-scope: STATEMENT  # SQL 세션 객체마다 가지고 있는 로컬 캐시의 적용 범위를 STATEMENT로 설정
    # 스네이크 케이스를 카멜 케이스로 변환
    map-underscore-to-camel-case: true
    # 조회되는 값이 NULL일 경우 누락될 경우, 이를 방지하기 위해 Setter() 또는 Map의 put()을 호출
    call-setters-on-nulls: true
    # 마이바티스에서의 값이 NULL인 파라미터 처리
    jdbc-type-for-null: NULL
  # 매핑을 위한 클래스의 이름을 작성시, 해당 클래스가 속한 패키지 명 생략
  type-aliases-package: com.beani.ssata.domain.**.dto
  # 자체 정의한 타입 핸들러 등록
  type-handlers-package: com.beani.ssata.global.common.mybatis
  # 매퍼 XML 파일의 경로 설정
  mapper-locations:
    - classpath:mapper/*_mapper.xml
    - classpath:mapper/**/*_mapper.xml


# 로깅 레벨 설정
logging:
  level:
    root: info
    web: info